import { CastleQuestion } from '../types';

export const CASTLE_CHAMBER_QUESTIONS: CastleQuestion[] = [
  {
    id: 'q2_origin',
    number: 2,
    chamberName: 'Chamber of Mortal Origins',
    title: 'The Bloodline & Era',
    prompt: 'From which mortal realm, home city, or birth year does your spirit hail?',
    hint: 'State your origin, city, or the year you walked into this world.',
    placeholder: 'e.g. Born in Bangalore, 1999...',
    iconName: 'Compass',
    allowAnyAnswer: true,
    vampireFeedback: 'The archives of eternity record your mortal lineage.',
  },
  {
    id: 'q3_feast',
    number: 3,
    chamberName: 'The Feast of the Damned',
    title: 'The Dark Offering',
    prompt: 'What birthday delicacy, sacred elixir, or dish shall satisfy the court tonight?',
    hint: 'Name your favorite food, birthday treat, or feast item.',
    placeholder: 'e.g. Royal chocolate cake, blood red wine...',
    iconName: 'Utensils',
    allowAnyAnswer: true,
    vampireFeedback: 'The feast tables tremble in anticipation of your feast.',
  },
  {
    id: 'q4_wish',
    number: 4,
    chamberName: 'The Crypt of Whispers',
    title: 'The Secret Birthday Wish / Message',
    prompt: 'Speak, sing, or write your secret heartfelt birthday wish or tribute to the Castle Master.',
    hint: 'A special birthday wish, personal memory, or song tribute.',
    placeholder: 'e.g. Wishing you endless glory, happiness and immortality on your birthday...',
    iconName: 'Scroll',
    allowAnyAnswer: true,
    vampireFeedback: 'Your words echo through the stone vaults and warm the vampire heart.',
  },
  {
    id: 'q5_oath',
    number: 5,
    chamberName: 'The Altar of Immortality',
    title: 'The Eternal Oath',
    prompt: 'What sacred motto, phrase, or truth do you pledge to seal your eternal immortality?',
    hint: 'Speak a powerful quote, inside joke, or phrase to seal the quest.',
    placeholder: 'e.g. Long live Billaa, through shadow and light...',
    iconName: 'Crown',
    allowAnyAnswer: true,
    vampireFeedback: 'The pact is sealed in blood and stone. Your quest is complete!',
  },
];
